# -*- coding: utf-8 -*-
"""Alana Souza - 211_LP_Funcao_cc_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GTdJZp1HHAoAtKviAP8EP1jZx-M8sd1T

### 1. (Função com retorno com parâmetro) Faça um programa contendo uma função/método que receba por parâmetro um número e o multiplique por 2, retorne e apresente o resultado da função.
"""

def multiplicar(numero):
    r = numero * 2
    return r
def main():
    n = int (input('Informe um valor na main:   '))
    total = multiplicar(n)
    print('O resultado de',n,'* 2 =',total)
main()

"""### 2. (Função com retorno com parâmetro) Faça um programa contendo uma função/método que receba dois números via parâmetro, some os dois valores, retorne e apresente o resultado."""

def soma(numero1,numero2):
    st = numero1 + numero2
    return st
def main():
    n1 = float (input('Insira um numero:    '))
    n2 = float (input('Insira outro numero: '))
    total = soma(n1,n2)
    print('Resultado de',n1,'+',n2,'é: ',total)
main()

"""### 3. (Função com retorno com parâmetro) Faça um programa contendo uma função/método que receba um valor de porcentagem de aumento via parâmetro, aplique este aumento a um salário de um funcionário, retorne e apresente o novo salário."""

def porcentagem(percent):
    salarioNovo = ((1500 * percent) / 100) + 1500
    return salarioNovo
def main():
    percent = float (input('Digite a porcentagem de aumento em seu salario:    '))
    total = porcentagem(percent)
    print('O novo salário é de',total)
main()

"""### 4. (Função com retorno com parâmetro) Faça um programa contendo uma função/método que receba duas notas (P1, P2) calcule a média, chame outra função na main que avalie se este aluno esta aprovado ou reprovado retornando a str/string 'Aprovado' ou 'Reprovado'."""

def media (p1,p2):
    media_final = (p1 + p2) / 2
    if media_final >= 5:
        return str ('Aprovado')
    else:
        return str ('Reprovado')
def main():
    n1=float(input("Digite a primeira nota: "))
    n2=float(input("Digite a segunda nota: "))
    total = media(n1,n2)
    print(f'{total}')
main()

"""### 5. (Função com retorno com parâmetro) Faça um programa contendo uma função/método que receba um valor de porcentagem de aumento e um salário via parâmetro, aplique este aumento ao salário do funcionário. Na parte principal do programa, na chamada da função, utilize um laço de repetição para ler 10 salários, chame a função para aplicar o aumento e gerar o novo salário, ainda dentro da estrutura de repetição acumule os novos salários e ao final apresente quanto será gasto no novo salário. Também apresente qual será a diferença entre o que se pagava para todos os funcionário e o que será pago após o aumento."""

def porcentagem (porcento, salarios):
    aumento = salarios * (porcento / 100 + 1)
    return aumento
    
def main():
    total_salarios = 0
    porcent = float(input("Digite uma porcentagem de aumento: "))
    for i in range (2):
      salario = float(input("Digite o salário: "))
      total = porcentagem (porcent, salario)
      print(total)
      total_salarios = total_salarios + (total - salario)
      print('O total gasto com o aumentos dos salários é:',total_salarios)
      print(f'O total gasto com o salario {salario} a diferença é: {total - salario}')
      
main()

"""### 6. (Função com retorno com parâmetro) Faça um programa contendo algumas funções:
a) Função para construir um menu de opções para uma calculadora:

    Menu de cálculos
    1.   Número ao quadrado
    2.   Número ao cubo
    3.   Raiz do número
    4.   Raiz cúbica do número
    Qual é a opção desejada?

b) Desenvolva uma função para cada opção de cálculo.

Observação: Na chamada da função deve-se utilizar uma estrutura de repetição que permita diversos cálculos, quando o usuário quiser sair da calculadora digitará qualquer valor diferente dos **números** do menu.

A função de desenho/construção do menu, esta chamará todas as outras passando a elas o valor digitado.





"""

def aoquadrado(n1):
    quadrado = n1 ** 2
    return quadrado
def aocubo(n1):
    cubo = n1 ** 3
    return cubo
def raizn(n1):
    raizQua = n1 ** (1/2) 
    return raizQua
def raizc(n1):
    raizC = n1 ** (1/3)
    return raizC
def main():
    '''Menu de cálculos
    1.   Número ao quadrado
    2.   Número ao cubo
    3.   Raiz do número
    4.   Raiz cúbica do número
    Qual é a opção desejada?'''
    menu = float (input("Digite uma opção de calculadora: "))
    while menu >= 1 and menu <= 4:
        n1 = float (input("Digite um número para realizar a conta: "))
        if menu == 1:
            totalQ = aoquadrado(n1)
            print(f'\n o numero {n1} ao quadrado é {totalQ}\n')
        if menu == 2:
            totalC = aocubo(n1)
            print(f'\n o numero {n1} ao cubo é {totalC}\n')
        if menu == 3:
            totalR = raizn(n1)
            print(f'\n raiz quadrada de {n1} é {totalR}\n')
        if menu == 4:
            totalRC = raizc(n1)
            print(f'\n raiz cubica de {n1} é {totalRC}\n')
        menu = float (input("Digite uma opção de calculadora: "))
main()

"""### 7. (Função com retorno com parâmetro) Faça um programa contendo algumas funções:
a) Função para construir um menu de opções para uma calculadora:

    *** Minha Calculadora ***
    Digite um número.....: 
    Digite outro número..: 
        + Soma dois números
        - Subtrai dois números
        * Multiplica dois números
        / Divide dois números
    Qual opção deseja? 

b) Desenvolva uma função para cada opção de cálculo, **mas estas não terão retorno**.

Observação: Na chamada da função deve-se utilizar uma estrutura de repetição que permita diversos cálculos, quando o usuário quiser sair da calculadora digitará qualquer valor diferente dos **caracteres** do menu.

A função de desenho/construção do menu, chamará todas as outras passando a elas os valores digitados.

"""

def soma(n1,n2):
    somar = n1 + n2
    print(f'\n o numero {n1} + {n2} é {somar}\n')
def subtrai(n1,n2):
    subtrair = n1 - n2
    print(f'\n o numero {n1} - {n2} é {subtrair}\n')
def multiplica(n1,n2):
    multiplicar = n1 * n2
    print(f'\n o numero {n1} * {n2} é {multiplicar}\n')
def divide(n1,n2):
    dividir = n1 / n2
    print(f'\n o numero {n1} / {n2} é {dividir}\n')
def main():
    '''*** Minha Calculadora ***
Digite um número.....: 
Digite outro número..: 
    + Soma dois números
    - Subtrai dois números
    * Multiplica dois números
    / Divide dois números
Qual opção deseja? '''
    menu = str (input("Digite uma opção de calculadora: "))
    while menu == '+' or menu == '-' or menu == '*' or menu == '/':
        n1 = float (input("Digite um número para realizar a conta: "))
        n2 = float (input("Digite um número para realizar a conta: "))
        if menu == '+':
            soma(n1,n2)
        if menu == '-':
            subtrai(n1,n2)
        if menu == '*':
            multiplica(n1,n2)
        if menu == '/':
            divide(n1,n2)
        menu = str (input("Digite uma opção de calculadora: "))
main()

"""### 8. (Função com retorno com parâmetro) Faça um programa contendo algumas funções:
a) Função para construir um menu de opções para uma calculadora:

    *** Minha Calculadora ***
    Digite um número.....: 
    Digite outro número..: 
        + Soma dois números
        - Subtrai dois números
        * Multiplica dois números
        / Divide dois números
    Qual opção deseja? 

b) Desenvolva uma função para cada opção de cálculo.

Observação: Na chamada da função deve-se utilizar uma estrutura de repetição que permita diversos cálculos, quando o usuário quiser sair da calculadora digitará qualquer valor diferente dos **caracteres** do menu.

A função de desenho/construção do menu, chamará todas as outras passando a elas os valores digitados.
"""

def soma (n1,n2):
    soma = n1 + n2
    return soma
def subtrai (n1,n2):
    subtrai = n1 - n2
    return subtrai
def multiplica (n1,n2):
    multiplica = n1 * n2
    return multiplica
def divide (n1,n2):
    divide = n1 / n2
    return divide
def main():
    menu = input("Digite um sinal que deseja calcular: ")
    while menu == '+' or menu == '-' or menu == '*' or menu == '/':
        n1 = float(input("Digite um número para fazer o calculo: "))
        n2 = float(input("Digite um número para fazer o calculo: "))   
        if menu == '+':
            totalS = soma(n1,n2)
            print(f'A soma de {n1:0.0f} + {n2:0.0f} é {totalS:0.0f}')
        if menu == '-':
            totalSUB = subtrai(n1,n2)
            print(f'A subtração de {n1:0.0f} - {n2:0.0f} é {totalSUB:0.0f}')
        if menu == '*':
            totalM = multiplica(n1,n2)
            print(f'A multiplicação de {n1:0.0f} * {n2:0.0f} é {totalM:0.0f}')
        if menu == '/':
            totalD = divide (n1,n2)
            print(f'A divisão de {n1:0.0f} / {n2:0.0f} é {totalD:0.0f}')
        menu = input("Digite o sinal que deseja calcular para continuar ou digite qualquer outro para sair: ")
main()